### ISSUE TITLE
[ERROR]  [sourcedir] does not seem to be a btrfs subvolume

### ISSUE THREAD

**Issue by henfri** [bob1de/btrfs-backup#26]
Hello,

thanks for btrfs-backup!
I have tried to use it:
```
root@homeserver:/home/henfri# btrfs-backup /srv/DataPool/Fotos/ /mnt/test/
21:46:29  [INFO ]  --[ Started at Mon Oct  4 21:46:29 2021 ]---------
21:46:29  [INFO ]  Preparing endpoint /srv/DataPool/Fotos/snapshot ...
21:46:29  [ERROR]  /srv/DataPool/Fotos does not seem to be a btrfs subvolume
root@homeserver:/home/henfri# btrfs subvolume show /srv/DataPool/Fotos/ |head
Fotos
        Name:                   Fotos
        UUID:                   3b7f5796-c053-8940-9809-7dfde837a47f
        Parent UUID:            -
        Received UUID:          -
        Creation time:          2019-04-28 21:50:08 +0200
        Subvolume ID:           1381
        Generation:             1002070
        Gen at creation:        260
        Parent ID:              5

```
Any idea, what the reason could be?

Best regards,
Hendrik

**Comment by bob1de** [comment]
Hi Hendrik,

That's an interesting finding. Could you please run with `-v debug` and also post the contents of `/proc/mounts` (maybe you want to censor some values before).

Thanks
Robert

**Comment by bob1de** [comment]
And it would be interesting to see whether a backup can successfully be created using `--skip-fs-checks`.

**Comment by henfri** [comment]
Hello,

thanks for your reply. 
```
btrfs-backup -v debug /srv/DataPool/Fotos/ /mnt/test/Fotos1
20:36:21  [INFO ]  --[ Started at Tue Oct  5 20:36:21 2021 ]---------
20:36:21  [DEBUG]  --[ Settings ]------------------------------------
20:36:21  [DEBUG]  Enable btrfs debugging: False
20:36:21  [DEBUG]  Don't display progress: False
20:36:21  [DEBUG]  Don't take a new snapshot: False
20:36:21  [DEBUG]  Number of snapshots to keep: 0
20:36:21  [DEBUG]  Number of backups to keep: Any
20:36:21  [DEBUG]  Snapshot folder: snapshot
20:36:21  [DEBUG]  Snapshot prefix: None
20:36:21  [DEBUG]  Don't transfer snapshots: False
20:36:21  [DEBUG]  Don't send incrementally: False
20:36:21  [DEBUG]  Extra SSH config options: []
20:36:21  [DEBUG]  Use sudo at SSH remote host: False
20:36:21  [DEBUG]  Run 'btrfs subvolume sync' afterwards: False
20:36:21  [DEBUG]  Convert subvolumes to read-write before deletion: False
20:36:21  [DEBUG]  Remove locks for given destinations: False
20:36:21  [DEBUG]  Skip filesystem checks: False
20:36:21  [DEBUG]  Auto add locked destinations: False
20:36:21  [DEBUG]  Source: /srv/DataPool/Fotos/
20:36:21  [DEBUG]  Source endpoint: /srv/DataPool/Fotos/snapshot
20:36:21  [INFO ]  Preparing endpoint /srv/DataPool/Fotos/snapshot ...
20:36:21  [DEBUG]  Checking for btrfs filesystem: /srv/DataPool/Fotos
20:36:21  [DEBUG]    Reading mounts file: /proc/mounts
20:36:21  [DEBUG]    New best_match with fstype ext4: /
20:36:21  [DEBUG]    -> best_match_fstype is ext4, result is False
20:36:21  [ERROR]  /srv/DataPool/Fotos does not seem to be a btrfs subvolume
```

and

```
btrfs-backup -v debug --skip-fs-checks /srv/DataPool/Fotos/ /mnt/test/Fotos1
20:37:58  [INFO ]  --[ Started at Tue Oct  5 20:37:58 2021 ]---------
20:37:58  [DEBUG]  --[ Settings ]------------------------------------
20:37:58  [DEBUG]  Enable btrfs debugging: False
20:37:58  [DEBUG]  Don't display progress: False
20:37:58  [DEBUG]  Don't take a new snapshot: False
20:37:58  [DEBUG]  Number of snapshots to keep: 0
20:37:58  [DEBUG]  Number of backups to keep: Any
20:37:58  [DEBUG]  Snapshot folder: snapshot
20:37:58  [DEBUG]  Snapshot prefix: None
20:37:58  [DEBUG]  Don't transfer snapshots: False
20:37:58  [DEBUG]  Don't send incrementally: False
20:37:58  [DEBUG]  Extra SSH config options: []
20:37:58  [DEBUG]  Use sudo at SSH remote host: False
20:37:58  [DEBUG]  Run 'btrfs subvolume sync' afterwards: False
20:37:58  [DEBUG]  Convert subvolumes to read-write before deletion: False
20:37:58  [DEBUG]  Remove locks for given destinations: False
20:37:58  [DEBUG]  Skip filesystem checks: True
20:37:58  [DEBUG]  Auto add locked destinations: False
20:37:58  [DEBUG]  Source: /srv/DataPool/Fotos/
20:37:58  [DEBUG]  Source endpoint: /srv/DataPool/Fotos/snapshot
20:37:58  [INFO ]  Preparing endpoint /srv/DataPool/Fotos/snapshot ...
20:37:58  [DEBUG]  Destination: /mnt/test/Fotos1
20:37:58  [DEBUG]  Destination endpoint: /mnt/test/Fotos1
20:37:58  [INFO ]  Preparing endpoint /mnt/test/Fotos1 ...
20:37:58  [INFO ]  --[ Snapshotting ... ]----------------------------
20:37:58  [INFO ]  /srv/DataPool/Fotos -> /srv/DataPool/Fotos/snapshot/20211005-203758
20:37:58  [DEBUG]  Executing: ['btrfs', 'subvolume', 'snapshot', '-r', '/srv/DataPool/Fotos', '/srv/DataPool/Fotos/snapshot/20211005-203758']
20:38:03  [DEBUG]  Executing: ['sync']
20:38:04  [INFO ]  --[ Transferring ... ]----------------------------
20:38:04  [INFO ]  --[   To /mnt/test/Fotos1 ... ]-------------------
20:38:04  [DEBUG]  Building snapshot cache of /srv/DataPool/Fotos/snapshot ...
20:38:04  [DEBUG]  Populated snapshot cache of /srv/DataPool/Fotos/snapshot with 1 items.
20:38:04  [DEBUG]  Building snapshot cache of /mnt/test/Fotos1 ...
20:38:04  [DEBUG]  Populated snapshot cache of /mnt/test/Fotos1 with 0 items.
20:38:04  [DEBUG]  Planning transmissions ...
20:38:04  [INFO ]  Going to transfer 1 snapshot(s):
20:38:04  [INFO ]    20211005-203758
20:38:04  [DEBUG]  Returning 1 cached snapshots for /srv/DataPool/Fotos/snapshot.
20:38:04  [DEBUG]  Writing lock file: /srv/DataPool/Fotos/snapshot/.outstanding_transfers
20:38:04  [DEBUG]  Lock state for 20211005-203758 and lock_id /mnt/test/Fotos1 changed to True (parent = False)
20:38:04  [INFO ]  Sending 20211005-203758 ...
20:38:04  [INFO ]    No parent snapshot available, sending in full mode.
20:38:04  [DEBUG]  Checking for pv ...
20:38:04  [DEBUG]  Executing: ['pv', '--help']
20:38:04  [DEBUG]    -> pv is available
20:38:04  [DEBUG]  Executing: ['btrfs', 'send', '/srv/DataPool/Fotos/snapshot/20211005-203758']
20:38:04  [DEBUG]  Executing: ['pv']
20:38:04  [DEBUG]  Executing: ['btrfs', 'receive', '/mnt/test/Fotos1']
At subvol /srv/DataPool/Fotos/snapshot/20211005-203758
At subvol 20211005-203758
 340MiB 0:00:12 [16,0MiB/s] [                              <=>    
```

Interesting, isn't it?

Best regards,
Hendrik

**Comment by bob1de** [comment]
It recognizes / as an ext4 filesystem, please show your `/proc/mounts` file (maybe censored as said before).

And good to see it works with `--skip-fs-checks`.

**Comment by henfri** [comment]
Hello,

/ is an ext4 FS. But /srv/DataPool is btrfs.

The backup ran successfully

At subvol /srv/DataPool/Fotos/snapshot/20211005-203758
At subvol 20211005-203758
2,85GiB 0:01:26 [27,1MiB/s] [                                   <=>                                                                                          ]
 997GiB 9:03:55 [31,3MiB/s] [            <=>                                                                                                                 ]
05:41:59  [DEBUG]    -> PID 1568715 exited with return code 0
05:41:59  [DEBUG]    -> PID 1568716 exited with return code 0
05:42:14  [DEBUG]    -> PID 1568717 exited with return code 0
05:42:14  [DEBUG]  Returning 1 cached snapshots for /srv/DataPool/Fotos/snapshot.
05:42:14  [DEBUG]  Writing lock file: /srv/DataPool/Fotos/snapshot/.outstanding_transfers
05:42:23  [DEBUG]  Lock state for 20211005-203758 and lock_id /mnt/test/Fotos1 changed to False (parent = False)
05:42:23  [DEBUG]  Returning 1 cached snapshots for /mnt/test/Fotos1.
05:42:23  [INFO ]  --[ Transfers to /mnt/test/Fotos1 complete! ]-----
05:42:23  [INFO ]  --[ Cleaning up ... ]-----------------------------
05:42:23  [INFO ]  --[ Finished at Wed Oct  6 05:42:23 2021 ]--------
```
The mounts:
```
cat /proc/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=6063576k,nr_inodes=1515894,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1217320k,mode=755 0 0
/dev/md0 / ext4 rw,noatime,nodiratime,errors=remount-ro 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,size=4096k,nr_inodes=1024,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13522 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
/dev/sdd2 /srv/dev-disk-by-label-Daten btrfs rw,relatime,ssd,space_cache,subvolid=5,subvol=/ 0 0
tmpfs /tmp tmpfs rw,relatime 0 0
/dev/sde1 /srv/dev-disk-by-id-ata-ST4000DM005-2DP166_ZDH26KL5-part1 ext4 rw,noexec,relatime,jqfmt=vfsv0 0 0
/dev/sdb /media/678c601d-8d2e-4be0-9226-d20a6f772f8b ext4 rw,noexec,relatime,jqfmt=vfsv0 0 0
/dev/sdc2 /srv/dev-disk-by-label-DockerImages btrfs rw,noatime,ssd,discard,space_cache,subvolid=5,subvol=/ 0 0
/dev/sde2 /srv/dev-disk-by-label-Big6_no_Snap ext4 rw,noexec,relatime,jqfmt=vfsv0 0 0
/dev/sdf2 /srv/dev-disk-by-label-Big5_NoSnapraid ext4 rw,noexec,relatime,jqfmt=vfsv0 0 0
NoSnap:22d8c536-7984-4367-8d7a-7d492e81cccd /srv/22d8c536-7984-4367-8d7a-7d492e81cccd fuse.mergerfs rw,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
/dev/sdf1 /srv/dev-disk-by-label-Big5 ext4 rw,noexec,relatime,jqfmt=vfsv0 0 0
DataPool:22cd0c22-c75b-432a-b92b-73229607a8bd /media/22cd0c22-c75b-432a-b92b-73229607a8bd fuse.mergerfs rw,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
/dev/sdc2 /srv/dev-disk-by-label-DockerImages/Docker/btrfs btrfs rw,noatime,ssd,discard,space_cache,subvolid=5,subvol=/ 0 0
nsfs /run/docker/netns/default nsfs rw 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/44798f9a8135a4edf6ac2d081da8f8e091337d6f44bdd8675523e5f47326d228/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
nsfs /run/docker/netns/af53f3d9751e nsfs rw 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/c071a4229d93452d76202a319789a0fcc733f6b7e16ac5e0b7be81f2342d093a/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/d4cf04935017195cf2457ad961e05c847dcd7e8595909a6a572d33fd8d1d579d/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/809c322bb1403dec9547f3689b54e71c86ff25d3a4b4079b454cff4251fe8361/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
nsfs /run/docker/netns/f86d95b11a7d nsfs rw 0 0
nsfs /run/docker/netns/8c17a575c3c6 nsfs rw 0 0
nsfs /run/docker/netns/8de55e9b6569 nsfs rw 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/b724e4cd3bbb0f4b23af3d05231a16c17fb9008affdac915e3a6a683c90a56a5/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
nsfs /run/docker/netns/b1b2fe3047b6 nsfs rw 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/3e761496ce138e6e752ac6df9b8e7161eea06a24940f361e9ae34880294d012c/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
nsfs /run/docker/netns/1eed130276df nsfs rw 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/38397817748f6f639597afa96161dd21547b9e85e18cc63ccac690b44bd79adb/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
nsfs /run/docker/netns/98919a7892a6 nsfs rw 0 0
nsfs /run/docker/netns/e51c5f59487a nsfs rw 0 0
nsfs /run/docker/netns/296332c93e0b nsfs rw 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1 btrfs rw,noatime,space_cache,subvolid=5,subvol=/ 0 0
/dev/sda1 /run/bees/mnt/c4a6a2c9-5cf0-49b8-812a-0784953f9ba3 btrfs rw,relatime,space_cache,subvolid=5,subvol=/ 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Backups btrfs rw,noatime,space_cache,subvolid=1376,subvol=/Backups 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Bilderrahmen btrfs rw,noatime,space_cache,subvolid=1377,subvol=/Bilderrahmen 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Daten btrfs rw,noatime,space_cache,subvolid=1379,subvol=/Daten 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Dokumente btrfs rw,noatime,space_cache,subvolid=1380,subvol=/Dokumente 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Fotos btrfs rw,noatime,space_cache,subvolid=1381,subvol=/Fotos 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/HomeVideo btrfs rw,noatime,space_cache,subvolid=1382,subvol=/HomeVideo 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Musik btrfs rw,noatime,space_cache,subvolid=1384,subvol=/Musik 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Paperless btrfs rw,noatime,space_cache,subvolid=1385,subvol=/Paperless 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/Video btrfs rw,noatime,space_cache,subvolid=1388,subvol=/Video 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/tmp btrfs rw,noatime,space_cache,subvolid=1387,subvol=/tmp 0 0
/dev/sda1 /srv/dev-disk-by-label-DataPool1/vrp btrfs rw,noatime,space_cache,subvolid=1390,subvol=/vrp 0 0
/dev/sdh /mnt/test btrfs rw,relatime,space_cache,subvolid=5,subvol=/ 0 0
nsfs /run/docker/netns/dbb0f80bdcda nsfs rw 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/7ed5aa2d4144f2bf084ad51865634b7c15f4e572c3a0530dd22f9a6b07a8b0d6/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
shm /srv/dev-disk-by-label-DockerImages/Docker/containers/073728fac7b86cc5dfa323959d198487fbfaa3047c0f2ed0cb9232c802516114/mounts/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k 0 0
```
I know there is much that you most likely do not need...

Best regards,
Hendrik

**Comment by bob1de** [comment]
Hi,

I guess the relevant mount is

    /dev/sda1 /srv/dev-disk-by-label-DataPool1/Fotos btrfs rw,noatime,space_cache,subvolid=1381,subvol=/Fotos 0 0

However, you call btrfs-backup with `/srv/DataPool/Fotos` as source. Could it be that `/srv/DataPool` is a symlink to `/srv/dev-disk-by-label-DataPool1`? Currently btrfs-backup doesn't recognize symlinks in source or destination path, but I'll add a `realpath` call to handle such cases correctly.

**Comment by henfri** [comment]
Great find! That is it.
I confirm that the fix works.

Best regards,
Hendrik

**Comment by bob1de** [comment]
Cool, then I'll release 0.3.2 soon.

Best regards
Robert
